FISH-829 Create 5.2020.7 Release Notes
payara/Payara-Community-Documentation pull request #119
Opened 2020-12-02 16:11 UTC by MattGill98

2020-12-02 16:18 UTC, rdebusscher requested changes
Small correction ...

2020-12-02 16:18 UTC, rdebusscher commented on docs/modules/ROOT/pages/release-notes/release-notes-2020-7.adoc
> +As MicroProfile moves toward the 4.0 milestone, the Payara team has simultaneously been working to ready the Payara Platform for MicroProfile 4.0 compatibility. In this Payara Platform Community Rele
`As MicroProfile moves toward the 4.0 milestone` should be
`As MicroProfile moves toward the 4.0 final release, the Payara team ...`

2020-12-02 16:38 UTC, rdebusscher approved these changes

2020-12-04 15:21 UTC, cubastanley requested changes

2020-12-04 15:21 UTC, cubastanley commented on docs/modules/ROOT/pages/release-notes/release-notes-2020-7.adoc
> +realm name for client-cert login
Need to remove this one from the release notes pending new PR in community for Jakarta EE fix

2020-12-07 10:40 UTC, OndroMih commented on docs/modules/ROOT/pages/release-notes/release-notes-2020-7.adoc
> +realm name for client-cert login
```suggestion
```

2020-12-07 10:41 UTC, merged