FISH-961 Document MicroProfile 4.0 upgrade
payara/Payara-Community-Documentation pull request #130
Opened 2021-02-04 16:37 UTC by MeroRai

2021-02-04 19:44 UTC, rdebusscher requested changes

2021-02-04 19:44 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/microprofile/README.adoc
> +    <version>4.0</version>
Version 4.0 is broken, users need to use `4.0.1`

2021-02-04 21:05 UTC, fturizo approved these changes
Aside from @rdebusscher's comment, everything looks good

2021-02-05 12:44 UTC, MattGill98 requested changes
Good so far, and we link to the spec docs so not every little change needs documenting. There are, however, a few implementation details that need documenting.

Firstly, each individual spec page lists a version that needs changing. Secondly, off the top of my head:

__Health__
`MP_HEALTH_BACKWARD_COMPATIBILITY_ENABLED` doesn't work anymore I don't think.
`@Health` annotation isn't present anymore.

__OpenAPI__
New property `mp.openapi.schema.`

__Metrics__
Now contains advice on handling multiple apps.
Base and Vendor metrics are now "per-application"

__FT__
Changed back to using ManagedExecutors. I believe this was changed and then reverted, so the state of the docs may be correct on this one.

I'd strongly suggest reading the PR for each of these implementations (with the addition of Patrik's second FT PR) for details to make sure our docs are still valid.

2021-02-09 19:21 UTC, fturizo commented
@MattGill98, apologies for the late reply. Technically the specifics you mentioned should have been documented separately by the implementor of the changes of each spec, so keep this in mind for the future. Since we only document the main differences and proprietary functionality from the spec documents, here are my 2 cents on the changes you mentioned:

* Health:  We do mention the use of the config property and the annotation so indeed we need to update this
* OpenAPI: The property needs to be added to the table in the corresponding section
* Metrics: I reviewed the spec changes and didn't see any changes that we need to document
* FT: This one is confusing. Our docs establish that we allow the configurable executor in one place and then we later state the contrary, so this one needs to be fixed. @pdudits, can you clarify which one is it? 

@MeroRai, can you make the other changes part of this PR as well?

2021-02-09 19:34 UTC, MeroRai commented
@fturizo, I have document changes made in all of the MicroProfile specs. In regards, to the Fault Tolerance, it is broken (read the documentation for more info). I have discussed this with @MattGill98 and it will be fixed in the future release as it is too late to be fixed in the upcoming release.

2021-02-09 20:30 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
> +NOTE: On Payara Platform 5.2021.1, it is a known issue that the `set-fault-tolerance-configuration` command is broken and it can't be used to configure user-defined executor to run the fault toleranc
Should we mention here already that a default executor is used an no longer a dedicated executor?

2021-02-09 20:33 UTC, rdebusscher approved these changes
Some comments but can be merged as is.

2021-02-09 20:33 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/microprofile/healthcheck.adoc
> +|On invocation, all registered health checks annotated with `@Liveness`and `@Readiness` are performed and the results aggregated.
missing space ? 

`@Liveness`and

2021-02-09 21:55 UTC, fturizo commented
Looks good, @MeroRai. I did a couple of grammar and layout fixes prior to the merge.

2021-02-09 21:56 UTC, merged