[FISH-1034] - Payara 5.2021.1 Release Notes
payara/Payara-Community-Documentation pull request #131
Opened 2021-02-09 10:21 UTC by cubastanley

Release Notes for Payara 5.2021.1 Community Edition Release

TCK results will come later as a separate PR

2021-02-09 11:07 UTC, AlanRoth approved these changes

2021-02-09 11:15 UTC, rdebusscher requested changes

2021-02-09 11:15 UTC, rdebusscher commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-1.adoc
> +* [https://github.com/payara/Payara/pull/5014[FISH-791]] - Upgrade to Hazelcast 4
We should add a paragraph at the top that due to this upgrade of Hazelcast, rolling updates are not supported.

2021-02-09 11:15 UTC, rdebusscher commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-1.adoc
> +* Java EE 8 Applications
Add P 4.0 also here as supported API.

2021-02-09 13:37 UTC, rdebusscher approved these changes

2021-02-10 00:17 UTC, OndroMih requested changes

2021-02-10 00:17 UTC, OndroMih commented on docs/modules/ROOT/nav.adoc
> +** xref:release-notes/release-notes-2021-1.adoc[Payara Community 5.2021.1 Release Notes]
No need to duplicate the current release notes page here. Antora doesn't treat duplicate links nicely and would always jump in the sidebar to the page in the Overview even if users click on the link in the History of Release Notes section
```suggestion
```

2021-02-10 00:17 UTC, OndroMih commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-1.adoc
> +Following the 5.2020.7 release, we’ve upgraded our MicroProfile implementations to be compatible with the specifications present in version 4.0 of MicroProfile. You should be able to test your MicroP
```suggestion
Following the 5.2020.7 release, we’ve upgraded Payara Platform to be compatible with the specifications present in version 4.0 of MicroProfile. You should be able to test your MicroProfile 4.0 compatible applications using this Community release. If you discover any issues, or have any related questions, please raise them on our GitHub repository. 
```

2021-02-10 12:47 UTC, merged