merge var substitution pages
payara/Payara-Community-Documentation pull request #166
Opened 2021-06-01 08:19 UTC by shub8968

[SERV-607] - Merge Using Variables and Variable Types Pages

2021-06-01 14:23 UTC, AlanRoth commented
Can you rename the from README.adoc to 'Variables in the configuration'.

You also need to update the nav.adoc to not include the child pages, which are no longer needed and can be deleted

2021-06-01 19:05 UTC, shub8968 commented
> Can you rename the file from README.adoc to 'Variables in the configuration'.
> 
> ![image](https://user-images.githubusercontent.com/44968097/120339987-84717d80-c2ed-11eb-9331-b20aeb1c98d9.png)
> You also need to update the nav.adoc to not include the child pages, which are no longer needed and can be deleted

Hi @AlanRoth,

I have pushed commit on the above review comments.

2021-06-07 15:50 UTC, AlanRoth approved these changes

2021-06-18 11:50 UTC, AlanRoth requested changes
I think once these are resolved we can merge this. Very well done!

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/nav.adoc
> +**** xref:documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc[Certificate Realm - Principal Name, Group Names]
```suggestion
**** xref:documentation/payara-server/server-configuration/security/certificate-realm.adoc[Certificate Realm]
```

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc
> +Payara Server Community includes a feature that supports using exclusively the use of the Common-Name (`CN`) from a client
```suggestion
Payara Server includes a feature that supports using exclusively the use of the Common-Name (`CN`) from a client
```

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc
> += Certificate Realm: Principal Name, Group Names
```suggestion
= Certificate Realm
```

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc
> +[[certificate-realm-principal-name-group-names]]
```suggestion
[[certificate-realm]]
```

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc
> +Payara Server Community includes a feature that supports using exclusively the use of the Common-Name (`CN`) from a client
It will be easier to keep it platform agnostic, as the same information is in Enterprise - porting it will be easier in the future.

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/security/README.adoc
> +* xref:documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc[Certificate Realm: Principal Name, Group Names]
```suggestion
* xref:documentation/payara-server/server-configuration/security/certificate-realm.adoc[Certificate Realm]
```

2021-06-18 11:50 UTC, AlanRoth commented on docs/modules/ROOT/nav.adoc
> +**** xref:documentation/payara-server/server-configuration/security/certificate-realm-principal-group-name.adoc[Certificate Realm - Principal Name, Group Names]
Remember to rename the file too

2021-06-30 08:11 UTC, AlanRoth approved these changes

2021-07-21 15:20 UTC, AlanRoth commented
Keep in mind README is now renamed to Overview.adoc with `:Ordinal: 900` attribute at the very first line of the file. 

The nav.adoc conflicts can be easily resolved by running the `./generate-nav.sh` script, the result should be idempotent and should place the correct files in the correct places to resolve the conflicts

2021-07-21 15:59 UTC, merged