FISH-1423 Documentation
payara/Payara-Community-Documentation pull request #169
Opened 2021-06-09 15:26 UTC by kalinchan

2021-06-09 15:54 UTC, rdebusscher requested changes

2021-06-09 15:54 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/enabling-jlink-event-expansion.adoc
> +When escaping characters in the CLI and Asadmin multimode using the \ character JLink removes the escape character for any character. This occured due to JLink updating from 2.x to 3.x, previously, t
JLine instead of JLink

2021-06-09 15:54 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/enabling-jlink-event-expansion.adoc
> +When escaping characters in the CLI and Asadmin multimode using the \ character JLink removes the escape character for any character. This occured due to JLink updating from 2.x to 3.x, previously, t
Can you describe the link with the events as mentioned in the title?

2021-06-09 16:01 UTC, AlanRoth requested changes
I would also add some examples of scenarios where users may wish to enable this feature, under a 'Usage' or 'Examples' heading after the 'Enabling JLine Event Expansion'

2021-06-09 16:03 UTC, AlanRoth commented
Also small pet peeve but I would rename the file to 'Enable JLine Event Expansion'

2021-06-10 08:58 UTC, kalinchan commented
@AlanRoth  @rdebusscher I have made the suggested changes

2021-06-14 12:41 UTC, rdebusscher requested changes
Can you briefly describe or link to a description of what JLine Event expansion is/does.

2021-06-14 12:41 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/Enable-JLine-Event-Expansion.adoc
> +. Tyoe the following command
Typo

2021-06-16 08:59 UTC, rdebusscher approved these changes

2021-06-16 09:18 UTC, AlanRoth approved these changes
LGTM

2021-06-16 11:37 UTC, merged