FISH-1654: Log To Console and Verbose mode.
payara/Payara-Community-Documentation pull request #185
Opened 2021-07-05 14:19 UTC by rdebusscher

2021-07-08 14:56 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +
Add a introductory section that explains what Log To Console does.

2021-07-08 14:56 UTC, AlanRoth commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +When in verbose mode, the log to Console option will also be active, regardless of the initial value in the _logging.properties_ as otherwise, no log output would be visible on the console. Once star
This sentence could be condensed a little and put under a 'Enabling/Disabling' subheading.

```suggestion
== Enabling
To enable the `Log to Console` option you simply have to start the Server or Instance with the verbose option.

[source, shell]
----
asadmin start domain --verbose
----

When using verbose mode, the log to Console option will also be active, regardless of the initial value in the _logging.properties_  file. Once started in verbose mode, you can use the Admin Console or the asadmin CLI to change this option.

NOTE: If Verbose mode is not used, the `java.util.ConsoleHandler` will not have a console attached to the process and will not be able to log to a console.

=== Disable Log To Console Using The Admin Console

To configure the `Log to Console` option using Admin Console, you can navigate to `Configurations > ${your-config} > Logger Settings > General > Log To File`

image:logging/log_to_file.png[Log to Console disabled]

=== Disable Log To File Using A `asadmin` Command

Use the following command to enable or disabled logging to the console:

[source, shell]
----
asadmin> set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logtoConsole=false
----
```

2021-08-06 11:47 UTC, OndroMih requested changes
Some things missing from Alan's suggestions and I added also my suggestions.

2021-08-06 11:47 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> += Log To Console
```suggestion
= Logging To Console
```

2021-08-06 11:47 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +== Enabling
```suggestion
[[enable]]
== Enable Logging To Console
```

2021-08-06 11:47 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +== Using the Admin Console
```suggestion
== Disable Logging To Console Using Admin Console
```

2021-08-06 11:47 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +== Using an `asadmin` command
```suggestion
== Disable Logging To File Using Asadmin CLI
```
Current name is Asadmin CLI: https://payara.atlassian.net/wiki/spaces/MARK/pages/2387247181/Feature+Re-naming

2021-08-06 11:52 UTC, OndroMih approved these changes

2021-08-06 11:52 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> += Logging To Console
```suggestion
= Log To Console
```

2021-08-06 11:54 UTC, OndroMih approved these changes

2021-08-06 11:54 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +== Disable Logging To Console Using Admin Console
```suggestion
== Configure Logging To Console Using Admin Console
```

2021-08-06 11:54 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +== Disable Logging To File Using Asadmin CLI
```suggestion
== Configure Logging To File Using Asadmin CLI
```

2021-08-06 11:55 UTC, merged

2021-08-06 11:58 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/logging/log-to-console.adoc
> +== Configure Logging To File Using Asadmin CLI
I've fixed the typo (File -> Console) in this commit after merging this PR: https://github.com/payara/Payara-Community-Documentation/commit/b6520676f0995a9d55f3562badd5082188199693