FISH-385 Multitenant OpenID Connect
payara/Payara-Community-Documentation pull request #191
Opened 2021-07-13 23:49 UTC by OndroMih

2021-07-14 17:05 UTC, fturizo requested changes
Looks good, minor changes needed

2021-07-14 17:05 UTC, fturizo commented on docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
> +_Since 5.2021.5_
According to the new style guide, we have decided to stop using this disclaimer

2021-07-14 17:05 UTC, fturizo commented on docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
> +By default, the same configuration of the OpenID connector is applied for the whole application, for all authentication attempts. This is for performance reasons. The OpenID connector also supports r
re-evaluating

2021-07-14 17:05 UTC, fturizo commented on docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
> +To enable reevaluating the configuration for each user session, set the MicroProfile Configuration property `payara.security.openid.sessionScopedConfiguration` to `true`. To specify it directly in th
Should be: "To enable the re-evaluation of the configuration per user session, ..."

2021-07-14 17:05 UTC, fturizo commented on docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
> +* enable session-scoped OpenID Connect configuration
Capitalize the sentences in the list

2021-07-14 17:05 UTC, fturizo commented on docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
> +Create `OpenidConfigBean` class with the `tokenEndpointURL` method. This class will be a CDI bean that injects `HttpServletRequest` to get information about which tenant to use. It will also inject `
Create an `OpenIDConfigBean` class

2021-07-14 17:05 UTC, fturizo commented on docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
>  _Since 5.2020.3_
According to the new style guide, we have decided to stop using this disclaimer, so better to remove it now.

2021-07-15 21:16 UTC, OndroMih commented
FISH-385 is postponed to a later release, do not merge this PR before the upcoming release.

2021-08-17 09:26 UTC, merged