SERV-642 Merge Rest Monitoring pages
payara/Payara-Community-Documentation pull request #196
Opened 2021-07-20 10:30 UTC by AlanRoth

Merged
- asadmin-commands.adoc
- configuring-rest-monitoring
- using-rest-monitoring.adoc

2021-07-21 21:39 UTC, fturizo requested changes
Changes needed

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +----
This section is technical "common-knowledge" and would be present in the existing GF manuals, so I think that it is redundant

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +INFO Only the READ Operation is supported.
This sentence seems to be out of place

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +----
`[source, json]` missing

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +INFO Only the READ Operation is supported.
Again, out-of-place sentence

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +----
`[source, json]` missing

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +*attribute*: The MBean attribute upon which the operation will be executed. If omitted, all attributes of the MBean will be involved in the operation.
This information should be put in a bullet list

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +----
`[source, shell]` missing

2021-07-21 21:39 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +----
`[source, json]` missing

2021-07-22 14:13 UTC, AlanRoth commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +technical preview, so some things may not work quite as intended.
I missed this bit! It is not needed indeed

2021-07-22 18:33 UTC, fturizo reviewed
Couple of small changes needed before merging

2021-07-22 18:33 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +NOTE This requires secure admin to be enabled.
NOTE:

2021-07-22 18:33 UTC, fturizo commented on docs/modules/ROOT/pages/Technical Documentation/Payara Server Documentation/Logging and Monitoring/Monitoring Service/REST Monitoring/Rest Monitoring.adoc
> +INFO Only the READ Operations are supported currently
INFO:

2021-07-22 18:34 UTC, fturizo approved these changes

2021-07-29 20:36 UTC, merged