[QACI-5514] - 5.2021.6 Release Notes + TCK Results
payara/Payara-Community-Documentation pull request #234
Opened 2021-08-13 15:11 UTC by cubastanley

Title

2021-08-13 15:30 UTC, rdebusscher requested changes

2021-08-13 15:30 UTC, rdebusscher commented on docs/modules/ROOT/pages/jakartaee-certification/5.2021.6/tck-results-full-5.2021.5.adoc
> +[[tck-results]]
Wrong filename .5 instead of .6

2021-08-13 15:30 UTC, rdebusscher commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-6.adoc
> +* [https://github.com/payara/Payara/pull/5359[FISH-1345]] - EE9 Transformer does not recognize the CDI 3.0 namespace in beans.xml; interceptor ingnored.
typo in `ingnored`.  (It was also on the Jira title)

2021-08-13 17:00 UTC, debbiehoffman requested changes

2021-08-13 17:00 UTC, debbiehoffman commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-6.adoc
> += Release notes - Payara Platform Development - Version 5.2021.6
Please capitalize Notes.  and change Development to Community, like this:
Release Notes - Payara Platform Community 5.2021.6

2021-08-16 14:36 UTC, debbiehoffman approved these changes

2021-08-16 14:40 UTC, rdebusscher approved these changes

2021-08-16 14:52 UTC, merged