FISH-5785 document create and delete system asadmin commands
payara/Payara-Community-Documentation pull request #259
Opened 2021-10-15 10:56 UTC by aubi

Documentation for create-service and _delete-service; based on man pages, added SystemD Linux support.

2021-10-18 10:01 UTC, OndroMih commented
Portion of this PR is copied from https://github.com/eclipse-ee4j/glassfish/blob/master/docs/reference-manual/src/main/jbake/content/create-service.adoc, which is under the EPL or GPL license. We currently don't use any license for this repository, we need to decide whether we use EPL or GPL so that it's compatible with GlassFish docs, or revisit how we can use the EPL-licensed pieces of GlassFish documentation.

2021-10-18 14:33 UTC, OndroMih requested changes

2021-10-18 14:33 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/server-management-commands.adoc
> +[[example]]
```suggestion
[[example-delete-service]]
```

2021-10-18 14:33 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/server-management-commands.adoc
> +Deleting a Service on a Linux System using SystemD init. This example deletes a service for the default domain on a system that is running Linux and SystemD. It is necessary to inform SystemD about d
```suggestion
=== Example: Deleting a Service on a Linux System using SystemD

This example deletes a service for the default domain on a system that is running Linux and SystemD. It is necessary to inform SystemD about deleting the script by running systemctl daemon-reload.
```

2021-11-04 15:51 UTC, Pandrex247 approved these changes

2021-11-05 11:43 UTC, merged