5.2021.10 Release Notes and TCK Results
payara/Payara-Community-Documentation pull request #283
Opened 2021-12-13 17:03 UTC by cubastanley

Title

2021-12-13 17:07 UTC, kalinchan approved these changes
LGTM

2021-12-14 09:19 UTC, rdebusscher requested changes

2021-12-14 09:19 UTC, rdebusscher commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-10.adoc
> +[https://github.com/payara/ecosystem-security-connectors/pull/145[FISH-5745]] Allow 'extraParameters' to be Specified via MP Config
This does not render correctly, an empty line must be between each line.

2021-12-14 11:52 UTC, OndroMih approved these changes

2021-12-14 11:57 UTC, OndroMih requested changes

2021-12-14 11:57 UTC, OndroMih commented on docs/modules/ROOT/pages/release-notes/release-notes-2021-10.adoc
> +[https://github.com/payara/Payara/pull/5492[FISH-5851]] [https://github.com/payara/Payara/pull/5492[Community Contribution - chrjohn]] Prevent NPE in com.sun.jts.CosTransactions.RecoveryManager
```suggestion
[https://github.com/payara/Payara/pull/5492[FISH-5851]] [https://github.com/chrjohn[Community Contribution - chrjohn]] Prevent NPE in com.sun.jts.CosTransactions.RecoveryManager
```

2021-12-14 11:57 UTC, OndroMih approved these changes

2021-12-14 12:41 UTC, rdebusscher approved these changes

2021-12-15 10:49 UTC, merged