FISH-5987 Remove TLS 1.0 and 1.1 and SSL3
payara/Payara-Community-Documentation pull request #299
Opened 2022-03-24 10:10 UTC by kalinchan

2022-03-25 15:52 UTC, fturizo approved these changes
Looks good.

2022-04-19 08:22 UTC, Pandrex247 requested changes
Should this be going to master? These were removed from the Payara 6 branch

2022-04-19 08:31 UTC, Pandrex247 requested changes

2022-04-19 08:31 UTC, Pandrex247 commented on docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/protocols/protocols-asadmin.adoc
> -        [--ssl3tlsciphers ssl3tlsciphers]
See comment on main PR - I'm not sure we should be removing this option

2022-04-21 08:09 UTC, Pandrex247 approved these changes

2022-04-22 08:44 UTC, merged