Transfer readme from archived Github repo containing Docker Image usage.
payara/Payara-Community-Documentation pull request #74
Opened 2020-10-02 14:31 UTC by rdebusscher

Transfer of the readme files of the archived Github repo containing Docker Image usage.

This is the basis to start improved and updated Payara Docker Image usage.

2020-10-05 12:52 UTC, rdebusscher commented
Updated the documentation to current state of Docker Image.

2020-10-05 13:15 UTC, OndroMih commented
Should we add info about where to find Payara Enterprise Docker Images too? Or just in the Enterprise docs?

2020-10-05 13:19 UTC, OndroMih commented
The page `docker-images.adoc` should be modified too. The following sentence is out of date:

```
Payara Services Limited provides Docker Images for the Payara Platform and updates them with every public release.
```
It should be more like:
```
Payara Services Limited provides Docker Images for the Payara Platform Community and updates them with every release.
```

And at the bottom of the page we could mention that Payara Platform Enterprise Docker Images are available in a private repository for Payara Enterprise customers.

2020-10-05 15:50 UTC, OndroMih requested changes

2020-10-05 15:50 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-server-usage.adoc
> +* `${SCRIPT_DIR}/init_*.sh` scripts that you may provide for custom use as waiting or initializing during startup, *before* Glassfish kicks in.
```suggestion
* `${SCRIPT_DIR}/init_*.sh` scripts that you may provide for custom use as waiting or initializing during startup, *before* Payara Server starts.
```

2020-10-05 15:50 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc
> +The context root of the deployed application(s) is determined based on the file name of the artifact which is deployed. Form Payara Micro version 5.191 on, you can explicitly define the value of the
"From version" not needed, it's already specified above.

```suggestion
The context root of the deployed application(s) is determined based on the file name of the artifact which is deployed. You can explicitly define the value of the context root using the `--contextroot` option, including deploying the application on the root itself ( `/`, specify *ROOT* as option value).
```

2020-10-05 15:50 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc
> +By default the image has the Data Grid enabled and instances of Payara Micro will form a Data Grid if they can see each other over multicast. Typically this will occur on a single host.
The last sentence doesn't make any sense to me.

```suggestion
By default the image has the Data Grid enabled and instances of Payara Micro will form a Data Grid if they can see each other over multicast. 
```

2020-10-05 15:50 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc
> +To speed up boot time the Data Grid can be disabled by modifying the CMD to add `--nocluster`
```suggestion
If you don't intend to form a cluster and want to speed up boot time, you can disable Data Grid by modifying the CMD to add `--nocluster`
```

2020-10-05 15:50 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc
> +* `MEM_MAX_RAM_PERCENTAGE` - Value for the JVM parameter `-XX:MaxRAMPercentage` that indicate the percentage of memory assigned to the container that can be used by the Java Process. By default this
```suggestion
* `MEM_MAX_RAM_PERCENTAGE` - Value for the JVM parameter `-XX:MaxRAMPercentage` that indicates the percentage of memory assigned to the container that can be used by the Java Process. By default this is _70_.
```

2020-10-05 17:34 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc
> +The command used in the Quick start above, will start the Zulu JDK 8 version. If you need the Zulu JDK 11 version, you need to add the `-jdk11` suffix to the image name.
It is not a good practice to use the LATEST (or jdk11 tag here) as you do not have control over the moment when a newer version of Payara is used). That is the reason i isn't mentioned.

2020-10-05 17:45 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-server-usage.adoc
> +* `ADMIN_PASSWORD` - The password used for accessing the server in combination with user name defined in  `ADMIN-USER`. By default this is `admin`.
ADMIN_PASSWORD is used to define the password for the admin user. See this line in d dockerfile.

````
echo "AS_ADMIN_PASSWORD=\nAS_ADMIN_NEWPASSWORD=${ADMIN_PASSWORD}" > /tmp/password-change-file.txt \
`````

The ADMIN_USER is effectively read only.

2020-10-05 17:50 UTC, rdebusscher commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-server-usage.adoc
> +* `AS_ADMIN_MASTERPASSWORD` - The master password to pass to Payara Server. This is overriden if one is specified in the `$PASSWORD_FILE`.
correct, was wrong in the old documentation

2020-10-06 08:17 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-server-usage.adoc
> +* `ADMIN_PASSWORD` - The password used for accessing the server in combination with user name defined in  `ADMIN-USER`. By default this is `admin`.
Yes. This happens at build time when the base image is built. If ADMIN_PASSWORD is set in a derived Dockerfile or when a container is started, it has no effect. That's why it's effectively read only.

If would need to be picked up by one of the init script to have any effect after the base image is built.

2020-10-06 09:17 UTC, OndroMih requested changes

2020-10-06 09:17 UTC, OndroMih commented on docs/modules/ROOT/pages/documentation/ecosystem/docker-images.adoc
> +Payara Enterprise customers have access to a private Docker repository containing Docker Images containing the Payara Enterprise Edition. These images are maintained every month. They receive JDK upd
```suggestion
TIP: Payara Enterprise customers have access to a private Docker repository containing Docker Images containing the Payara Enterprise Edition. These images are maintained every month. They receive JDK updates, expired Security certificates are removed and OS updates can be requested.
```

2020-10-07 13:11 UTC, OndroMih approved these changes

2020-10-08 20:06 UTC, merged