FISH-710 Create 5.2020.6 Release Notes
payara/Payara-Community-Documentation pull request #98
Opened 2020-11-05 16:39 UTC by MattGill98

2020-11-05 22:21 UTC, fturizo requested changes
Looks good, but a minor fix is needed.

2020-11-05 22:21 UTC, fturizo commented on docs/modules/ROOT/pages/release-notes/release-notes-2020-6.adoc
> +* [https://github.com/payara/Payara/pull/4972[FISH-429]] - ``JACC Policy Provider: Failed Permission Check'' warning in logs
Minor typo here: The opening double quotes don't match to the closing one

2020-11-05 22:39 UTC, MattGill98 commented on docs/modules/ROOT/pages/release-notes/release-notes-2020-6.adoc
> +* [https://github.com/payara/Payara/pull/4972[FISH-429]] - ``JACC Policy Provider: Failed Permission Check'' warning in logs
```suggestion
* [https://github.com/payara/Payara/pull/4972[FISH-429]] - 'JACC Policy Provider: Failed Permission Check' warning in logs
```

2020-11-06 09:36 UTC, MarkWareham approved these changes

2020-11-06 09:36 UTC, merged